[package]
name = "x11_idle_reporter"
version = "0.1.0"
edition = "2021"

[dependencies]
ctrlc = "3.4.1"
x11 = { version = "2.21.0", features = ["xss", "xlib"] }
paho-mqtt = "0.12.0"
clap = { version = "4.4.7", features = ["derive"] }
